<?php

use NG\Registry;
use NG\Uri;
$helper = $this->helper;
$baseUrl = Uri::baseUrl();
$config = Registry::get('config');
$controllerPath = Registry::get('controllerPath');
$controllerName = Registry::get('controllerName');
$viewData = isset($this->viewData) ? $this->viewData : array();

$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";


?>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <button data-toggle="modal" data-target="#dialog-add" class="btn waves-effect waves-light btn-success">
                    <i class="fas fa-plus-circle"></i>&nbsp; Tambah Data
                </button>
            </div>
        </div>
    </div>
    <?php if ($viewSuccess) { ?>
        <div class="col-md-12">
            <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewSuccess ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($viewAlert) { ?>
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewAlert ?>
            </div>
        </div>
    <?php } ?>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered display no-wrap datatable" style="width:100%">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th width="60"></th>
                                    <th>Menu</th>
                                    <th>Aksi</th>
                                    <th>Nama</th>
                                    <th>Deskripsi</th>
                                </tr>
                                </thead>
                                <?php
                                if ($viewData) {
                                    $data = $helper->getArrayValue($viewData, "data");
                                    $total = $helper->getArrayValue($viewData, "total");

                                    if ($data){
                                        ?>
                                        <tbody>
                                        <?php
                                        $no = 0;
                                        foreach ($data as $item) {
                                            $no++;
                                            $id = $helper->getArrayValue($item, "id");
                                            $item["DT_RowId"] = $id;
                                            $item["no"] = $no;
                                            ?>
                                            <tr data-key="id" data-value="<?php echo $id; ?>">
                                                <td width="20" data-key="no" data-text="no" align="right" data-value="<?php echo $no; ?>" data-edit="false"><?php echo $item["no"] ?></td>

                                                <td width="60" data-key="" data-edit="false" data-input="action">
                                                        <textarea style="display: none" class="item-data" data-id="<?php echo $id ?>">
                                                            <?php echo json_encode($item, true) ?>
                                                        </textarea>
                                                    <button data-id="<?php echo $id ?>" class="btn btn-sm btn-warning btn-item-edit">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <button data-id="<?php echo $id ?>" class="btn btn-sm btn-danger btn-item-delete">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </td>
                                                <td data-key="idmenu"><?php echo $item["idmenu"] ?></td>
                                                <td data-key="idaction"><?php echo $item["action"] ?></td>
                                                <td data-key="name"><?php echo $item["name"] ?></td>
                                                <td data-key="description"><?php echo $item["description"] ?></td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                        <?php
                                    }
                                }
                                ?>
                                <!--
                                <tfoot>
                                <tr>
                                    <th>Name</th>
                                    <th>Kunci</th>
                                    <th>Jenis</th>
                                    <th>Target</th>
                                    <th>Target</th>
                                </tr>
                                </tfoot>
                                -->
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
