<?php
$render = new Render();
?>

<!-- ======= Topbar ======= -->
<?php echo $render->childRender($this->section("topbar"), null); ?>

<!-- ======= Header ======= -->
<?php echo $render->childRender($this->section("header"), null); ?>

<main id="main">
    <div class="container" data-aos="fade-up">
        <h2 class="title mt-4 mb-3">404</h2>
        <h4>Ups! Laman tidak ditemukan</h4>
        <div class="col-lg-12" data-aos="fade-up" data-aos-delay="100">
            <p class="text-danger">
                Sayangnya Anda mengakses halaman yang tidak dikenal
            </p>
        </div>
    </div>
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<?php echo $this->section("footer"); ?>
