<?php

use NG\Registry;
use NG\Uri;
$helper = $this->helper;
$baseUrl = Uri::baseUrl();
$config = Registry::get('config');
$controllerPath = Registry::get('controllerPath');
$controllerName = Registry::get('controllerName');
$viewData = isset($this->viewData) ? $this->viewData : array();
$viewDataMeta = isset($this->viewDataMeta) ? $this->viewDataMeta : array();

$viewAction = isset($this->viewAction) ? $this->viewAction : "";

$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

if ($viewDataMeta) {
    $dataMeta = $helper->getArrayValue($viewDataMeta, 'data');
}
?>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <button data-toggle="modal" data-target="#dialog-add" class="btn waves-effect waves-light btn-success">
                    <i class="fas fa-plus-circle"></i>&nbsp; Tambah Data
                </button>
            </div>
        </div>
    </div>
    <?php if ($viewSuccess) { ?>
        <div class="col-md-12">
            <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewSuccess ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($viewAlert) { ?>
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewAlert ?>
            </div>
        </div>
    <?php } ?>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered display no-wrap datatable" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="20">No</th>
                                    <th width="40"></th>
                                    <th width="30">Foto</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Jenis</th>
                                    <th>Status</th>
                                    <?php
                                    if ($dataMeta) {
                                        foreach ($dataMeta as $itemMeta) {
                                            $colName = $itemMeta["name"];
                                            ?>
                                            <th><?php echo $colName ?> </th>
                                            <?php
                                        }
                                    }
                                    ?>
                                </tr>
                                </thead>
                                <?php
                                if ($viewData) {
                                    $data = $helper->getArrayValue($viewData, "data");
                                    $total = $helper->getArrayValue($viewData, "total");

                                    if ($data){
                                        ?>
                                        <tbody>
                                        <?php
                                        $no = 0;
                                        foreach ($data as $item) {
                                            $no++;
                                            $id = $helper->getArrayValue($item, "id");
                                            $idtype = $helper->getArrayValue($item, "idtype");
                                            $image = $helper->getArrayValue($item, "image");
                                            $active = $helper->getArrayValue($item, "active");
                                            $code = $helper->getArrayValue($item, "code");
                                            $statusName = "Tidak Aktif";
                                            if ($active) $statusName = "Aktif";

                                            $fileImage = ROOT . DS . UPLOADS . DS . PROFILE . DS . strtolower($code) . DS . $image;

                                            $imageSrc = $baseUrl .  "asset/img/user.png";
                                            if (file_exists($fileImage)){
                                                if (is_file($fileImage)){
                                                    $imageSrc = $baseUrl . "image/profile/" . strtolower($code) . "/$image";
                                                }
                                            }

                                            if ($dataMeta) {
                                                $detailKeys = $helper->getArrayValue($item, "detail-keys");
                                                $detailValues = $helper->getArrayValue($item, "detail-values");

                                                $arrDetailKeys = null;
                                                $arrDetailValues = null;

                                                if ($detailKeys) {
                                                    $arrDetailKeys = explode("***", $detailKeys);
                                                    $arrDetailValues = explode("***", $detailValues);
                                                    for ($k = 0; $k < count($arrDetailKeys); $k++) {
                                                        $itemDetailKeys = $arrDetailKeys[$k];
                                                        $itemDetailValues = $arrDetailValues[$k];
                                                        $item[$itemDetailKeys] = $itemDetailValues;
                                                    }
                                                }
                                            }

                                            $item["DT_RowId"] = $id;
                                            $item["no"] = $no;
                                            $item["status-name"] = $statusName;
                                            $item["image-path"] = $imageSrc;

                                            ?>
                                            <tr data-key="id" data-value="<?php echo $id; ?>">
                                                <td width="20" data-key="no" data-text="no" align="right" data-value="<?php echo $no; ?>" data-edit="false"><?php echo $item["no"] ?></td>

                                                <td width="60" data-key="" data-edit="false" data-input="action">
                                                        <textarea style="display: none" class="item-data" data-id="<?php echo $id ?>">
                                                            <?php echo json_encode($item, true) ?>
                                                        </textarea>
                                                    <!--
                                                    <button data-id="<?php /*echo $id */?>" class="btn btn-sm btn-warning btn-item-edit">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    -->
                                                    <a href="<?php echo $baseUrl . "$controllerPath/profil/$id" ?>" class="btn btn-sm btn-warning">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                    <button data-id="<?php echo $id ?>" class="btn btn-sm btn-danger btn-item-delete">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </td>
                                                <td data-key="image">
                                                    <img style="max-height: 32px; max-width: 32px" class="img-fluid" src="<?php echo $imageSrc ?>" alt="<?php echo $item["name"] ?>">
                                                </td>
                                                <td data-key="name"><?php echo $item["name"] ?></td>
                                                <td data-key="email"><?php echo $item["email"] ?></td>
                                                <td data-key="type"><?php echo $item["type-name"] ?></td>
                                                <td data-key="active"><?php echo $statusName ?></td>
                                                <?php if ($dataMeta) {
                                                    foreach ($dataMeta as $itemMeta) {
                                                        $colSlug = $itemMeta["slug"];
                                                        ?>
                                                        <td data-key="<?php echo $colSlug ?>"><?php echo $item[$colSlug] ?></td>
                                                        <?php
                                                    }
                                                    ?>

                                                <?php } ?>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                        <?php
                                    }
                                }
                                ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
