<?php

use NG\Uri;
$baseUrl = Uri::baseUrl();
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";
$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewUnique = isset($this->viewUnique) ? $this->viewUnique : "";
?>

<div class="modal fade dialog-wizard"
     data-keyboard="false"
     data-backdrop="static">

    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content bg-gradient-white">

            <form action="<?php echo $baseUrl ?>login" method="post">
                <div class="modal-header bg-gradient-light">
                    <h4 class="modal-title">Masuk</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <?php if ($viewAlert) { ?>
                                <div class="alert alert-danger alert-dismissible">
                                    <span><?php echo $viewAlert ?></span>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input name="email" type="text" class="form-control" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input name="password" type="password" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <button type="submit" class="btn btn-outline-dark">Masuk</button>
                </div>
            </form>

        </div>
    </div>
</div>

