<?php
use NG\Uri;
$baseUrl = Uri::baseUrl();
$config = $this->config;
$helper = $this->helper;
$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

?>

<div class="modal modal-danger fade" id="dialog-delete">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <form role="form" id="form-delete" method="post">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h4 class="modal-title text-light">Hapus Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true" class="text-white">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-error-body">
                    <input type="hidden" id="del-gallery-id" name="del-gallery-id" data-field="id">
                    Yakin ingin menghapus data?
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="submit" name="action" class="btn btn-danger" value="delete">Ya</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="dialog-edit" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content">
            <form role="form" id="form-edit" method="post">
                <div class="modal-header bg-warning">
                    <h4 class="modal-title text-dark">Ubah Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="edit-name" class="col-form-label">Nama</label>
                                <input type="hidden" id="edit-id" name="edit-id" data-field="id">
                                <input type="text" class="form-control item-data" id="edit-name" name="edit-name" placeholder="Nama" data-field="name">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="edit-tag" class="col-form-label">Tag</label>
                                <input type="text" class="form-control item-tag" id="edit-tag" name="edit-tag" placeholder="Tag" data-field="tag">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" name="action" class="btn btn-warning" value="edit">
                        <i class="fas fa-save"></i>&nbsp;&nbsp;Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

