<?php
use NG\Uri;
$baseUrl = Uri::baseUrl();
$config = $this->config;
$helper = $this->helper;
$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";
$viewDataMeta = isset($this->viewDataMeta) ? $this->viewDataMeta : array();
$viewDataMetaParent = isset($this->viewDataMetaParent) ? $this->viewDataMetaParent : "";
$dataMeta = null;
if ($viewDataMeta) {
    $dataMeta = $helper->getArrayValue($viewDataMeta, "data");
}

$dataMetaParent = null;
if ($viewDataMetaParent) {
    $dataMetaParent = $helper->getArrayValue($viewDataMetaParent, "data");
}

$viewDataCmsType = isset($this->viewDataCmsType) ? $this->viewDataCmsType : array();
$dataCmsType = null;
if ($viewDataCmsType) {
    $dataCmsType = $helper->getArrayValue($viewDataCmsType, 'data');
}
$dataTarget = array(
    array("id" => "user", "name" => "Pengguna"),
    /*
    array("id" => "all", "name" => "Semua"),
    array("id" => "ref", "name" => "Referensi"),
    array("id" => "posting", "name" => "Posting"),
    array("id" => "letter", "name" => "Surat"),
    */
);
if ($dataCmsType) {
    foreach ($dataCmsType as $itemCmsType) {
        $itemCmsType["id"] = "posting-" . $itemCmsType["slug"];
        $itemCmsType["name"] = "Posting: " . $itemCmsType["name"];
        $dataTarget[] = $itemCmsType;
    }
}
?>

<div class="modal modal-danger fade" id="dialog-delete">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <form role="form" id="form-delete" method="post">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h4 class="modal-title text-light">Hapus Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true" class="text-white">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-error-body">
                    <input type="hidden" id="del-meta-id" name="del-meta-id" data-field="id">
                    Yakin ingin menghapus data?
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="submit" name="action" class="btn btn-danger" value="delete">Ya</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="dialog-add" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content">
            <form role="form" id="form-add" method="post">
                <div class="modal-header bg-success">
                    <h4 class="modal-title text-light">Tambah Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="add-name" class="col-form-label">Meta</label>
                                <input type="text" class="form-control" id="add-name" name="add-name" placeholder="Nama">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="add-type" class="col-form-label">Jenis</label>
                                <select class="form-control select2bs4" id="add-type" name="add-type" data-type="select">
                                    <?php
                                    $dataType = array(
                                        array("id" => "text", "name" => "Teks Pendek"),
                                        array("id" => "textarea", "name" => "Teks Panjang"),
                                        array("id" => "number", "name" => "Angka"),
                                        array("id" => "select", "name" => "Pilihan Tunggal"),
                                        array("id" => "multi-select", "name" => "Pilihan Multi"),
                                        array("id" => "date", "name" => "Tanggal"),
                                        array("id" => "time", "name" => "Waktu"),
                                        array("id" => "datetime", "name" => "Tanggal dan Waktu"),
                                        array("id" => "auto-number", "name" => "Nomor Otomatis"),
                                    );
                                    foreach ($dataType as $itemType){
                                        $idType = $itemType["id"];
                                        $nameType = $itemType["name"];
                                        ?>
                                        <option value="<?php echo $idType ?>"><?php echo $nameType ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="add-target" class="col-form-label">Target Data</label>
                                <select class="form-control select2bs4" id="add-target" name="add-target" data-type="select">
                                    <option value="">Tidak Ada</option>
                                    <?php
                                    foreach ($dataTarget as $itemTarget){
                                        $idTarget = $itemTarget["id"];
                                        $nameTarget = $itemTarget["name"];
                                        ?>
                                        <option value="<?php echo $idTarget ?>"><?php echo $nameTarget ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="add-source" class="col-form-label">Sumber Data</label>
                                <select class="form-control select2bs4" id="add-source" name="add-source" data-type="select">
                                    <option value="">Tidak Ada</option>
                                    <?php
                                    if ($dataMeta) {
                                        foreach ($dataMeta as $itemMeta){
                                            $idSource = "meta#" . $itemMeta["slug"];
                                            $nameSource = "Meta: " . $itemMeta["name"];
                                            ?>
                                            <option value="<?php echo $idSource ?>"><?php echo $nameSource ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="add-parent" class="col-form-label">Kepala</label>
                                <select class="form-control select2bs4" id="add-parent" name="add-parent" data-type="select">
                                    <option value="0">Tidak Ada</option>
                                    <?php
                                    foreach ($dataMetaParent as $itemParent){
                                        $idParent = $itemParent["id"];
                                        $nameParent = $itemParent["name"];
                                        ?>
                                        <option value="<?php echo $idParent ?>"><?php echo $nameParent ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" name="action" class="btn btn-success" value="add">
                        <i class="fas fa-save"></i>&nbsp;&nbsp;Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="dialog-edit" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content">
            <form role="form" id="form-edit" method="post">
                <div class="modal-header bg-warning">
                    <h4 class="modal-title text-dark">Ubah Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="edit-name" class="col-form-label">Meta</label>
                                <input type="hidden" class="form-control" id="edit-id" name="edit-id" data-field="id">
                                <input type="text" class="form-control" id="edit-name" name="edit-name" placeholder="Nama" data-field="name">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="edit-slug" class="col-form-label">Kunci</label>
                                <input type="text" class="form-control" id="edit-slug" name="edit-slug" placeholder="Kunci" data-field="slug">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="edit-type" class="col-form-label">Jenis</label>
                                <select class="form-control select2bs4" id="edit-type" name="edit-type" data-type="select" data-field="type">
                                    <?php
                                    $dataType = array(
                                        array("id" => "text", "name" => "Teks Pendek"),
                                        array("id" => "textarea", "name" => "Teks Panjang"),
                                        array("id" => "number", "name" => "Angka"),
                                        array("id" => "select", "name" => "Pilihan Tunggal"),
                                        array("id" => "multi-select", "name" => "Pilihan Multi"),
                                        array("id" => "date", "name" => "Tanggal"),
                                        array("id" => "time", "name" => "Waktu"),
                                        array("id" => "datetime", "name" => "Tanggal dan Waktu"),
                                        array("id" => "auto-number", "name" => "Nomor Otomatis"),
                                    );
                                    foreach ($dataType as $itemType){
                                        $idType = $itemType["id"];
                                        $nameType = $itemType["name"];
                                        ?>
                                        <option value="<?php echo $idType ?>"><?php echo $nameType ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="edit-target" class="col-form-label">Target Data</label>
                                <select class="form-control select2bs4" id="edit-target" name="edit-target" data-type="select" data-field="target">
                                    <option value="">Tidak Ada</option>
                                    <?php
                                    foreach ($dataTarget as $itemTarget){
                                        $idTarget = $itemTarget["id"];
                                        $nameTarget = $itemTarget["name"];
                                        ?>
                                        <option value="<?php echo $idTarget ?>"><?php echo $nameTarget ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="edit-source" class="col-form-label">Sumber Data</label>
                                <select class="form-control select2bs4" id="edit-source" name="edit-source" data-type="select" data-field="source">
                                    <option value="">Tidak Ada</option>
                                    <?php
                                    if ($dataMeta) {
                                        foreach ($dataMeta as $itemMeta){
                                            $idSource = "meta#" . $itemMeta["slug"];
                                            $nameSource = "Meta: " . $itemMeta["name"];
                                            ?>
                                            <option value="<?php echo $idSource ?>"><?php echo $nameSource ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="edit-parent" class="col-form-label">Kepala</label>
                                <select class="form-control select2bs4" id="edit-parent" name="edit-parent" data-type="select" data-field="parent">
                                    <option value="0">Tidak Ada</option>
                                    <?php
                                    foreach ($dataMetaParent as $itemParent){
                                        $idParent = $itemParent["id"];
                                        $nameParent = $itemParent["name"];
                                        ?>
                                        <option value="<?php echo $idParent ?>"><?php echo $nameParent ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" name="action" class="btn btn-warning" value="edit">
                        <i class="fas fa-save"></i>&nbsp;&nbsp;Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

