<?php

use NG\Registry;
use NG\Uri;
$helper = $this->helper;
$baseUrl = Uri::baseUrl();
$config = Registry::get('config');
$controllerPath = Registry::get('controllerPath');
$controllerName = Registry::get('controllerName');
$viewData = isset($this->viewData) ? $this->viewData : array();

$viewAction = isset($this->viewAction) ? $this->viewAction : "";
$viewAction = strtolower($viewAction);

$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

?>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <input name="add-files" id="add-files" type="file" style="display: none" multiple />
                        <label for="add-files" style="cursor: pointer" class="btn waves-effect waves-light btn-success">
                            <i class="fas fa-plus-circle"></i>&nbsp; Tambah Data
                        </label>
                    </div>
                    <div class="col-md-12">
                        <div id="progress-file" class="progress mt-2" >
                            <div id="progress-bar-file" class="progress-bar progress-bar-striped progress-bar-animated"
                                 role="progressbar" aria-valuenow="0" aria-valuemin="0"
                                 aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if ($viewSuccess) { ?>
        <div class="col-md-12">
            <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewSuccess ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($viewAlert) { ?>
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewAlert ?>
            </div>
        </div>
    <?php } ?>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered display no-wrap datatable" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="20">No</th>
                                    <th width="40"></th>
                                    <th width="50">Thumb</th>
                                    <th width="50">Tanggal</th>
                                    <th>Nama</th>
                                    <th width="30">Ext</th>
                                    <th width="50">Ukuran</th>
                                    <th width="150">Alamat</th>
                                </tr>
                                </thead>
                                <?php
                                if ($viewData) {
                                    $data = $helper->getArrayValue($viewData, "data");
                                    $total = $helper->getArrayValue($viewData, "total");

                                    if ($data){
                                        ?>
                                        <tbody>
                                        <?php
                                        $no = 0;
                                        foreach ($data as $item) {
                                            $no++;

                                            $id = $helper->getArrayValue($item, "id");
                                            $name = $helper->getArrayValue($item, "name");
                                            $code = $helper->getArrayValue($item, "code");
                                            $date = $helper->getArrayValue($item, "date");
                                            $ext = $helper->getArrayValue($item, "ext");
                                            $tag = $helper->getArrayValue($item, "tag");
                                            $dateForm = str_replace("-", "", $date);

                                            $path = $baseUrl . "gallery/$dateForm/$name.$ext";

                                            $daterev = $helper->unreverseDate($date);

                                            $galleryDir = $helper->getGalleryDir($date);
                                            $filePath = $galleryDir . DS . $code . "." . $ext;
                                            $size = 0;

                                            if (file_exists($filePath)){
                                                $size = filesize($filePath);
                                            }

                                            $sizeText = $helper->formatSizeUnits($size);

                                            $item["DT_RowId"] = $id;
                                            $item["no"] = $no;
                                            $item["path"] = $path;
                                            $item["daterev"] = $daterev;
                                            $item["size"] = $sizeText;

                                            ?>
                                            <tr data-key="id" data-value="<?php echo $id; ?>">
                                                <td width="20" data-key="no" data-text="no" align="right" data-value="<?php echo $no; ?>" data-edit="false"><?php echo $item["no"] ?></td>
                                                <td width="40" data-key="" data-edit="false" data-input="action">
                                                        <textarea style="display: none" class="item-data" data-id="<?php echo $id ?>">
                                                            <?php echo json_encode($item, true) ?>
                                                        </textarea>
                                                    <button data-id="<?php echo $id ?>" class="btn btn-sm btn-warning btn-item-edit">
                                                        <i class="fas fa-edit"></i>
                                                    </button>
                                                    <button data-id="<?php echo $id ?>" class="btn btn-sm btn-danger btn-item-delete">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </td>
                                                <td width="50" data-key="image" data-input="action" class="text-center">
                                                    <embed src="<?php echo $path ?>" width="50" height="50">
                                                </td>

                                                <td data-key="date" data-text="daterev" data-edit="false"><?php echo $daterev; ?></td>
                                                <td data-key="name" ><?php echo $name; ?></td>
                                                <td data-key="ext" data-edit="false"><?php echo $ext; ?></td>
                                                <td data-key="size" align="right" data-edit="false"><?php echo $sizeText; ?></td>
                                                <td data-key="path" data-edit="false">
                                                    <input class="form-control gallery-path" type="url" value="<?php echo $path; ?>" readonly>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                        <?php
                                    }
                                }
                                ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
