<?php

use NG\Registry;
use NG\Uri;
$helper = $this->helper;
$baseUrl = Uri::baseUrl();
$config = Registry::get('config');
$controllerPath = Registry::get('controllerPath');
$controllerName = Registry::get('controllerName');
$viewData = isset($this->viewData) ? $this->viewData : array();

$viewFilterType = isset($this->viewFilterType) ? $this->viewFilterType : 1;

$viewAction = isset($this->viewAction) ? $this->viewAction : "";
$viewAction = strtolower($viewAction);

$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

$viewDataMeta = isset($this->viewDataMeta) ? $this->viewDataMeta : array();
$dataMeta = null;
if ($viewDataMeta) {
    $dataMeta = $helper->getArrayValue($viewDataMeta, "data");
}

$viewDataType = isset($this->viewDataType) ? $this->viewDataType : array();
$dataType = null;
if ($viewDataType) {
    $dataType = $helper->getArrayValue($viewDataType, "data");
}

$editURL = $baseUrl . strtolower($controllerPath) . "/$viewAction/$viewFilterType/edit";
?>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="form-inline">
                    <div class="form-group">
                        <a href="<?php echo $baseUrl . "$controllerPath/$viewAction/$viewFilterType/baru" ?>" class="btn waves-effect waves-light btn-success">
                            <i class="fas fa-plus-circle"></i>&nbsp; Tambah Data
                        </a>
                    </div>
                    <form role="form" method="post" class="form-inline mx-sm-3">
                        <div class="form-group mx-sm-3">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <label for="filter-type" class="input-group-text">Jenis</label>
                                </div>
                                <div class="input-group-append">
                                    <select class="form-control select2bs4" id="filter-type" name="filter-type">
                                        <?php
                                        foreach ($dataType as $itemType){
                                            $selected = "";
                                            $idType = $itemType["id"];
                                            $nameType = $itemType["name"];
                                            if ($viewFilterType == $idType) $selected = "selected";
                                            ?>
                                            <option value="<?php echo $idType ?>" <?php echo $selected ?>><?php echo $nameType ?></option>
                                            <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mx-sm-3">
                            <div class="input-group">
                                <button type="submit" name="action" class="btn btn-warning" value="filter">
                                    <i class="fas fa-filter"></i>&nbsp; Tampilkan
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <?php if ($viewSuccess) { ?>
        <div class="col-md-12">
            <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewSuccess ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($viewAlert) { ?>
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <?php echo $viewAlert ?>
            </div>
        </div>
    <?php } ?>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered display no-wrap datatable" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="20">No</th>
                                    <th width="40"></th>
                                    <th>Judul</th>
                                    <th>Kunci</th>
                                    <th width="60">Jenis</th>
                                    <th width="100">Tanggal</th>
                                </tr>
                                </thead>
                                <?php
                                if ($viewData) {
                                    $data = $helper->getArrayValue($viewData, "data");
                                    $total = $helper->getArrayValue($viewData, "total");

                                    if ($data){
                                        ?>
                                        <tbody>
                                        <?php
                                        $no = 0;
                                        foreach ($data as $item) {
                                            $no++;
                                            $id = $helper->getArrayValue($item, "id");
                                            $type = $helper->getArrayValue($item, "type");
                                            $slug = $helper->getArrayValue($item, "slug");
                                            $date = $helper->getArrayValue($item, "date");
                                            $title = $helper->getArrayValue($item, "title");

                                            if ($date) {
                                                $dateunrev = $helper->unreverseDate($date);
                                            }

                                            $typeName = "";
                                            if ($type) {
                                                foreach ($dataType as $itemType) {
                                                    if ($type == $itemType["id"]) {
                                                        $typeName = $itemType["name"];
                                                        break;
                                                    }
                                                }
                                            }

                                            $item["DT_RowId"] = $id;
                                            $item["no"] = $no;

                                            ?>
                                            <tr data-key="id" data-value="<?php echo $id; ?>">
                                                <td width="20" data-key="no" data-text="no" align="right" data-value="<?php echo $no; ?>" data-edit="false"><?php echo $item["no"] ?></td>

                                                <td width="60" data-key="" data-edit="false" data-input="action">
                                                        <textarea style="display: none" class="item-data" data-id="<?php echo $id ?>">
                                                            <?php echo json_encode($item, true) ?>
                                                        </textarea>
                                                    <a title="Edit" href="<?php echo "$editURL/$id" ?>" class="btn btn-sm btn-warning">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                    <button data-id="<?php echo $id ?>" class="btn btn-sm btn-danger btn-item-delete">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </td>
                                                <td><?php echo $title; ?></td>
                                                <td><?php echo $slug; ?></td>
                                                <td><?php echo $typeName; ?></td>
                                                <td><?php echo $dateunrev; ?></td>
                                            </tr>
                                            <?php
                                        }
                                        ?>
                                        </tbody>
                                        <?php
                                    }
                                }
                                ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
