<?php

use NG\Uri;
$baseUrl = Uri::baseUrl();
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";
$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
?>
<div class="modal fade dialog-wizard"
     data-keyboard="false"
     data-backdrop="static">

    <div class="modal-dialog modal-md modal-dialog-centered">
        <div class="modal-content bg-gradient-white">

            <div class="modal-header bg-gradient-light">
                <h4 class="modal-title">Pemasangan</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-warning alert-dismissible">
                    <span><?php echo $viewSuccess ?></span>
                </div>
                <hr />
                <p class="mt-3 mb-1">
                    <a href="<?php echo $baseUrl ?>masuk">Kembali ke Masuk</a>
                </p>
            </div>
        </div>
    </div>
</div>
