<?php
use NG\Uri;
$baseUrl = Uri::baseUrl();
$config = $this->config;
$helper = $this->helper;
$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

?>

<div class="modal fade" id="dialog-alert-error">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <form role="form" method="post">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h4 class="modal-title text-light" id="dialog-alert-error-title">Kesalahan</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true" class="text-white">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="dialog-alert-error-text">

                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="dialog-alert-success">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <form role="form" method="post">
            <div class="modal-content">
                <div class="modal-header bg-success">
                    <h4 class="modal-title text-light" id="dialog-alert-success-title">Berhasil</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true" class="text-white">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="dialog-alert-success-text">

                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </form>
    </div>
</div>

