<?php

use NG\Registry;
use NG\Uri;

$baseUrl = Uri::baseUrl();
$helper = $this->helper;
$config = Registry::get('config');

$viewTitle = isset($this->viewTitle) ? $this->viewTitle : "";
$viewDescription = isset($this->viewDescription) ? $this->viewDescription : "";
$viewImage = isset($this->viewImage) ? $this->viewImage : "";
$viewKeywords = isset($this->viewKeywords) ? $this->viewKeywords : "";
$viewBreadcrumb = isset($this->viewBreadcrumb) ? $this->viewBreadcrumb : array();

$controllerPath = Registry::get('controllerPath');
$controllerName = Registry::get('controllerName');

$viewAction = isset($this->viewAction) ? $this->viewAction : "";
$viewId = isset($this->viewId) ? $this->viewId : "";
$viewSub = isset($this->viewSub) ? $this->viewSub : "";

?>
<!DOCTYPE html>
<html dir="ltr" lang="id">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $baseUrl ?>asset/img/logo.png">
    <title><?php echo "$viewTitle - " . $config['SITE_TITLE'] ?></title>

    <meta name="baseURL" content="<?php echo $baseUrl ?>" />
    <meta name="view-controller" content="<?php echo strtolower($controllerPath)  ?>" />
    <meta name="view-action" content="<?php echo strtolower($viewAction) ?>" />
    <meta name="view-id" content="<?php echo $viewId ?>" />
    <meta name="view-sub" content="<?php echo $viewSub ?>" />

    <!-- Custom CSS -->
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/css/style.min.css" rel="stylesheet">

    <link rel="stylesheet" href="<?php echo $baseUrl ?>plugin/jquery.richtext/richtext.min.css">
    <link rel="stylesheet" href="<?php echo $baseUrl ?>plugin/select2/css/select2.min.css">
    <link rel="stylesheet" href="<?php echo $baseUrl ?>plugin/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link rel="stylesheet" href="<?php echo $baseUrl ?>plugin/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css">
    <link rel="stylesheet" href="<?php echo $baseUrl ?>plugin/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- ============================================================== -->
<!-- Preloader - style you can find in spinners.css -->
<!-- ============================================================== -->
<div class="preloader">
    <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
    </div>
</div>
<!-- ============================================================== -->
<!-- Main wrapper - style you can find in pages.scss -->
<!-- ============================================================== -->
<div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <?php $this->template("Layout/Topbar"); ?>
    <!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <?php $this->template("Layout/Sidebar"); ?>
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1"><?php echo $viewTitle ?></h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb m-0 p-0">
                                <?php
                                    if ($viewBreadcrumb) {
                                        foreach ($viewBreadcrumb as $itemBreadcrumb) {
                                            $bcUrl = $helper->getArrayValue($itemBreadcrumb, "url");
                                            $bcTitle = $helper->getArrayValue($itemBreadcrumb, "title");
                                            ?>
                                            <li class="breadcrumb-item"><a href="<?php echo $bcUrl ?>"><?php echo $bcTitle ?></a></li>
                                <?php
                                        }
                                    }
                                ?>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <?php
            /* rendering View */
            $this->render();
            ?>
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center text-muted">
            Copyright &copy; <?php echo date("Y"); ?>
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
</div>

<?php $this->template("Layout/Alert"); ?>

<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- apps -->

<script src="<?php echo $baseUrl ?>plugin/jquery.richtext/jquery.richtext.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/select2/js/select2.full.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/moment/moment.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/bs-custom-file-input/bs-custom-file-input.min.js"></script>

<!-- apps -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/app-style-switcher.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/feather.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart//assets/extra-libs/sparkline/sparkline.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/sidebarmenu.js"></script>
<!--Custom JavaScript -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/custom.min.js"></script>
<!--This page JavaScript -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/c3/d3.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/c3/c3.min.js"></script>
<!--
<script src="<?php /*echo $baseUrl */?>plugin/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
<script src="<?php /*echo $baseUrl */?>plugin/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
-->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>

<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js"></script>

<script src="<?php echo $baseUrl ?>script/Main.js"></script>
<script src="<?php echo $baseUrl ?>script/<?php echo ucfirst($controllerName) ?>.js"></script>

<!--
<script src="<?php /*echo $baseUrl */?>plugin/adminmart/assets/dist/js/pages/dashboards/dashboard1.min.js"></script>
-->
</body>
</html>
