<?php

use NG\Registry;
use NG\Uri;
$viewTitle = isset($this->viewTitle) ? $this->viewTitle : "";
$viewDescription = isset($this->viewDescription) ? $this->viewDescription : "";
$viewImage = isset($this->viewImage) ? $this->viewImage : "";
$viewKeywords = isset($this->viewKeywords) ? $this->viewKeywords : "";
$viewBreadcrumb = isset($this->viewBreadcrumb) ? $this->viewBreadcrumb : array();
$baseUrl = Uri::baseUrl();
$helper = $this->helper;
$config = Registry::get('config');

$controllerPath = Registry::get('controllerPath');
$controllerName = Registry::get('controllerName');

?>
<!DOCTYPE html>
<html dir="ltr" lang="id">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $baseUrl ?>plugin/adminmart/assets/images/favicon.png">
    <title><?php echo "$viewTitle - " . $config['SITE_TITLE'] ?></title>
    <!-- Custom CSS -->
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/css/style.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- ============================================================== -->
<!-- Main wrapper - style you can find in pages.scss -->
<!-- ============================================================== -->
<div id="main-wrapper">

    <div class="auth-wrapper d-flex no-block justify-content-center align-items-center position-relative">
        <?php
        /* rendering View */
        $this->render();
        ?>
    </div>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- apps -->
<!-- apps -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/app-style-switcher.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/feather.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart//assets/extra-libs/sparkline/sparkline.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/sidebarmenu.js"></script>
<!--Custom JavaScript -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/dist/js/custom.min.js"></script>
<!--This page JavaScript -->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/c3/d3.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/c3/c3.min.js"></script>
<!--
<script src="<?php /*echo $baseUrl */?>plugin/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
<script src="<?php /*echo $baseUrl */?>plugin/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
-->
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>

<script src="<?php echo $baseUrl ?>plugin/adminmart/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $baseUrl ?>script/<?php echo ucfirst($controllerName) ?>.js"></script>

<!--
<script src="<?php /*echo $baseUrl */?>plugin/adminmart/assets/dist/js/pages/dashboards/dashboard1.min.js"></script>
-->
</body>
</html>
