<?php
use NG\Uri;
$baseUrl = Uri::baseUrl();
$config = $this->config;
$helper = $this->helper;
$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

$viewDataInput = isset($this->viewDataInput) ? $this->viewDataInput : array();
$viewDataUser = isset($this->viewDataUser) ? $this->viewDataUser : array();
$viewDataPost = isset($this->viewDataPost) ? $this->viewDataPost : array();
$viewDataMeta = isset($this->viewDataMeta) ? $this->viewDataMeta : array();
$viewDataContent = isset($this->viewDataContent) ? $this->viewDataContent : '';

$dataInput = null;
$dataUser = null;
$dataPost = null;
$dataMeta = null;

$viewAlert = isset($this->viewAlert) ? $this->viewAlert : "";
$viewSuccess = isset($this->viewSuccess) ? $this->viewSuccess : "";

$viewPostId = isset($this->viewPostId) ? $this->viewPostId : 0;

if ($viewDataInput) {
    $dataInput = $helper->getArrayValue($viewDataInput, 'data');
}
if ($viewDataUser) {
    $dataUser = $helper->getArrayValue($viewDataUser, 'data');
}
if ($viewDataMeta) {
    $dataMeta = $helper->getArrayValue($viewDataMeta, 'data');
}

$todayYear = date("Y");
$todayMonth = date("m");

$dataMonthRomawi = null;
$dataYear = null;
$dataMonth = null;
$dataDate = null;
$dataDays = null;
for ($i = 0; $i <= 10; $i++){
    $dataYear[] = array("id" => $todayYear - $i, "name" => $todayYear - $i);
}
for ($i = 1; $i <= 31; $i++){
    $dataDate[] = array("id" => $i, "name" => $i);
}
$days = array('Ahad', 'Senin', 'Selasa', 'Rabu','Kamis','Jumat', 'Sabtu');
$months = array("Januari", "Februari", "Maret", "April", "Mei", "Juni",
    "Juli", "Agustus", "September", "Oktober", "November", "Desember",
);
for ($i = 1; $i <= 12; $i++){
    $dataMonthRomawi[] = array("id" => $i, "name" => $helper->romawi($i));
}
for ($i = 0; $i <= 11; $i++){
    $dataMonth[] = array("id" => $i + 1, "name" => $months[$i]);
}
for ($i = 0; $i <= 6; $i++){
    $dataDays[] = array("id" => $i, "name" => $days[$i]);
}
?>

<div class="modal modal-danger fade" id="dialog-delete">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <form role="form" id="form-delete" method="post">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h4 class="modal-title text-light">Hapus Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true" class="text-white">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-error-body">
                    <input type="hidden" id="del-letter-id" name="del-letter-id" data-field="id">
                    Yakin ingin menghapus data?
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="submit" name="action" class="btn btn-danger" value="delete">Ya</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="dialog-add" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form role="form" id="form-add" method="post">
                <div class="modal-header bg-success">
                    <h4 class="modal-title text-light">Tambah Data</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <?php
                        $allInput = array();
                        if ($dataMeta) {
                            foreach ($dataMeta as $item) {
                                $item["title"] = $item["name"];
                                $item["source"] = "";
                                $itemType = $item["type"];
                                $itemSlug = $item["slug"];
                                if (in_array($itemType, array('select', 'multi-select'))){
                                    $item["source"] = "meta#$itemSlug";
                                }
                                $allInput[] = array('input' => $item);
                            }
                        }
                        if ($dataInput) {
                            foreach ($dataInput as $item) {
                                $allInput[] = $item;
                            }
                        }
                        if ($allInput) {
                            $inputData = $viewData;
                            foreach ($allInput as $item) {
                                $input = $helper->getArrayValue($item, 'input');
                                $inputParentIds = $helper->getArrayValue($item, 'parent-ids');
                                $inputParentTitles = $helper->getArrayValue($item, 'parent-titles');
                                $inputParentSlugs = $helper->getArrayValue($item, 'parent-slugs');
                                $inputParentTypes = $helper->getArrayValue($item, 'parent-types');
                                $inputParentSources = $helper->getArrayValue($item, 'parent-sources');
                                $inputParentFormats = $helper->getArrayValue($item, 'parent-formats');

                                if ($input) {
                                    $inputTitle = $helper->getArrayValue($input, 'title');
                                    $inputSlug = $helper->getArrayValue($input, 'slug');
                                    $inputType = $helper->getArrayValue($input, 'type');
                                    $inputSource = $helper->getArrayValue($input, 'source');
                                    $inputFormat = $helper->getArrayValue($input, 'format');
                                    if ($inputTitle) {
                                        ?>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="edit-<?php echo $inputSlug ?>" class="col-form-label"><?php echo $inputTitle ?></label>
                                                <div class="input-group">
                                                    <?php
                                                    $helper->renderInput($inputTitle, $inputSlug, $inputType, $inputFormat, $inputSource, $inputData,
                                                        $dataUser, $dataYear, $dataMonth, $dataDate, $dataDays
                                                    );
                                                    if ($inputParentIds) {
                                                        $arrInputParentIds = explode("***", $inputParentIds);
                                                        $arrInputParentSlugs = explode("***", $inputParentSlugs);
                                                        $arrInputParentTitles = explode("***", $inputParentTitles);
                                                        $arrInputParentTypes = explode("***", $inputParentTypes);
                                                        $arrInputParentSources = explode("***", $inputParentSources);
                                                        $arrInputParentFormats = explode("***", $inputParentFormats);
                                                        for ($p = 0; $p < count($arrInputParentIds); $p++) {
                                                            $inputChildId = $helper->getArrayValue($arrInputParentIds, $p);
                                                            $inputChildSlug = $helper->getArrayValue($arrInputParentSlugs, $p);
                                                            $inputChildTitle = $helper->getArrayValue($arrInputParentTitles, $p);
                                                            $inputChildType = $helper->getArrayValue($arrInputParentTypes, $p);
                                                            $inputChildSource = $helper->getArrayValue($arrInputParentSources, $p);
                                                            $inputChildFormat = $helper->getArrayValue($arrInputParentFormats, $p);

                                                            $helper->renderInput($inputChildTitle, $inputChildSlug, $inputChildType,
                                                                $inputChildFormat, $inputChildSource, $inputData, $dataUser, $dataYear, $dataMonth,
                                                                $dataDate, $dataDays
                                                            );
                                                        }
                                                    }
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" name="action" class="btn btn-success" value="add">
                        <i class="fas fa-save"></i>&nbsp;&nbsp;Simpan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
